# Generated by Django 2.2.2 on 2019-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='biography_blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='birthday',
            field=models.DateField(),
        ),
    ]
